-- Extend form_quality to include 'Extreme_Cheat' and normalize legacy values

-- 1) Normalize any legacy values like 'Good' to a valid value
UPDATE public.submissions
SET form_quality = 'Competition'
WHERE form_quality = 'Good';

-- 2) Drop old CHECK constraint (assumes default autogenerated name)
ALTER TABLE public.submissions
DROP CONSTRAINT IF EXISTS submissions_form_quality_check;

-- 3) Add new CHECK constraint including 'Extreme_Cheat'
ALTER TABLE public.submissions
ADD CONSTRAINT submissions_form_quality_check
CHECK (form_quality IN ('Competition', 'Minor_Cheat', 'Major_Cheat', 'Extreme_Cheat'));


